# Generated by Django 5.0.6 on 2024-07-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='説明文')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnails/', verbose_name='サムネイル(空欄可)')),
                ('movie', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='動画')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
