# Generated by Django 5.0.6 on 2024-07-22 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=20, verbose_name='名前')),
                ('text', models.TextField(max_length=200, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='youtube.post', verbose_name='紐づく動画')),
            ],
        ),
    ]
